### ISSUE TITLE
Tensorflow 1.0 Support.

### ISSUE THREAD

**Issue by jostep** [douban/tfmesos#59]
Tensorflow has released 1.0 for a while with many APIs and files changed. We should consider support tensorflow 1.0.

**Comment by gengmao** [comment]
FYI, I am able to pip install tfmesos (using git+https://github.com/douban/tfmesos.git@master#egg=tfmesos) on top of the tensorflow/tensorflow:1.0.1 docker image and use tfrun to execute a distributed training. 

In this way pip won't re-install tensorflow so that you can use any tensorflow version with tfmesos, as long as it is higher than 0.8.0, as required in https://github.com/douban/tfmesos/blob/master/setup.py#L54
